export const paymentAuditActions = {
  membershipCheckoutRequested: 'MEMBERSHIP_CHECKOUT_REQUESTED',
  membershipCheckoutCreated: 'MEMBERSHIP_CHECKOUT_CREATED',
  paymentCheckoutCreated: 'PAYMENT_CHECKOUT_CREATED',
  paymentConfirmed: 'PAYMENT_CONFIRMED',
  paymentFailedConfirmed: 'PAYMENT_FAILED',
  paymentCancelled: 'PAYMENT_CANCELLED',
  webhookDuplicateIgnored: 'PAYMENT_WEBHOOK_DUPLICATE_IGNORED',
  webhookInvalid: 'PAYMENT_WEBHOOK_INVALID',
  membershipCheckoutFailed: 'MEMBERSHIP_CHECKOUT_FAILED',
  stripeCustomerCreated: 'STRIPE_CUSTOMER_CREATED',
  webhookReceived: 'PAYMENT_WEBHOOK_RECEIVED',
  webhookProcessed: 'PAYMENT_WEBHOOK_PROCESSED',
  webhookFailed: 'PAYMENT_WEBHOOK_FAILED',
  paymentSucceeded: 'MEMBERSHIP_PAYMENT_SUCCEEDED',
  paymentFailed: 'MEMBERSHIP_PAYMENT_FAILED',
  subscriptionUpdated: 'MEMBERSHIP_SUBSCRIPTION_UPDATED',
  subscriptionCancelled: 'MEMBERSHIP_SUBSCRIPTION_CANCELLED',
  revertedToFree: 'MEMBERSHIP_REVERTED_TO_FREE',
  dunningStarted: 'MEMBERSHIP_DUNNING_STARTED',
  dunningRetryDue: 'MEMBERSHIP_DUNNING_RETRY_DUE',
  dunningRecovered: 'MEMBERSHIP_DUNNING_RECOVERED',
  dunningSuspended: 'MEMBERSHIP_DUNNING_SUSPENDED',
  dunningCancelled: 'MEMBERSHIP_DUNNING_CANCELLED',
  paymentFailedNotice: 'MEMBERSHIP_PAYMENT_FAILED_NOTICE',
  gracePeriodStartedNotice: 'MEMBERSHIP_GRACE_PERIOD_STARTED_NOTICE',
  dunningStartedNotice: 'MEMBERSHIP_DUNNING_STARTED_NOTICE',
  dunningRetryNotice: 'MEMBERSHIP_DUNNING_RETRY_NOTICE',
  recoveredNotice: 'MEMBERSHIP_RECOVERED_NOTICE',
  suspendedNotice: 'MEMBERSHIP_SUSPENDED_NOTICE',
  cancelledNotice: 'MEMBERSHIP_CANCELLED_NOTICE',
} as const;


